name: Build Debian arm64

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:


jobs:
  linux-arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt install -y aha git make gcc g++ cmake pkg-config librtlsdr-dev whiptail libpq-dev

    - name: build AIS-catcher
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: upload artifact
      run: |
        mkdir -p output/plugins
        cp build/AIS-catcher output/
        cp plugins/* output/plugins/
        
    - name: Upload Artifacts linux-arm64
      uses: actions/upload-artifact@v3
      with:
        name: "AIS-catcher_linux-arm64"
        path: |
          output

  build-deb:
    runs-on: ubuntu-latest
    needs: linux-arm64
    
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: "AIS-catcher_linux-arm64"
 
      - name: Create package structure
        run: |
          mkdir -p .debpkg/usr/local/bin
          mkdir -p .debpkg/usr/share/aiscatcher/my-plugins
          ls -alR
          unzip *.zip
          cp AIS-catcher .debpkg/usr/local/bin/
          cp plugins/* .debpkg/usr/share/aiscatcher/my-plugins/
          chmod +x .debpkg/usr/local/bin/AIS-catcher

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst

      - uses: jiro4989/build-deb-action@v3
        with:
          package: AIS-catcher
          package_root: .debpkg
          maintainer: Greg Albrecht
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'arm64'
          desc: 'A multi-platform AIS Receiver'