name: Build Linux ARM64

on:
  push:
    tags:
      - '*'

jobs:
  build-artifact:
    runs-on: linux-arm64

    steps:
      - uses: actions/checkout@master
     
      - name: Install dependencies
        run: sudo apt install -y aha git make gcc g++ cmake pkg-config librtlsdr-dev whiptail libpq-dev build-essential

      - name: build ais-catcher
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create package structure
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/share/aiscatcher/my-plugins
          cp build/AIS-catcher .debpkg/usr/bin/ais-catcher
          cp plugins/* .debpkg/usr/share/aiscatcher/my-plugins/
          chmod +x .debpkg/usr/bin/ais-catcher

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          cp debian/service .debpkg/DEBIAN/ais-catcher.service
          cp debian/default .debpkg/DEBIAN/ais-catcher.default
          cp debian/postinst .debpkg/DEBIAN
          chmod 0755 .debpkg/DEBIAN/postinst

      - name: Run build-deb-action from jiro4989
        uses: jiro4989/build-deb-action@v3
        with:
          package: ais-catcher
          package_root: .debpkg
          maintainer: gba@snstac.com
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: 'A multi-platform AIS Receiver'

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@master
        with:
          name: artifact-deb
          path: ./*.deb

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset to GitHub
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true